# Generated by Django 3.1 on 2020-08-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(verbose_name='date of birth')),
                ('Address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('issue', models.CharField(max_length=1000)),
                ('profile_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
