# Generated by Django 3.1 on 2020-08-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200822_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateTimeField(default='01/01/01', verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
