# Generated by Django 3.1 on 2020-08-22 02:40

import datetime
from django.db import migrations, models
from django.utils.dateparse import parse_date


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200822_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateTimeField(default=parse_date('01/01/01'), verbose_name='date of birth'),
        ),
    ]
