# Generated by Django 3.1 on 2020-08-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200822_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=None, null=True, verbose_name='date of birth'),
        ),
    ]
