# Generated by Django 3.1 on 2020-08-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200822_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
